# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(478, 310)
        self.stackedWidget = QtWidgets.QStackedWidget(Widget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 461, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.addNewUserButton = QtWidgets.QPushButton(self.loginPage)
        self.addNewUserButton.setGeometry(QtCore.QRect(250, 190, 131, 41))
        self.addNewUserButton.setObjectName("addNewUserButton")
        self.verifyUserButton = QtWidgets.QPushButton(self.loginPage)
        self.verifyUserButton.setGeometry(QtCore.QRect(120, 190, 111, 41))
        self.verifyUserButton.setObjectName("verifyUserButton")
        self.usernameLabel = QtWidgets.QLabel(self.loginPage)
        self.usernameLabel.setGeometry(QtCore.QRect(100, 40, 61, 51))
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameEntry = QtWidgets.QLineEdit(self.loginPage)
        self.usernameEntry.setGeometry(QtCore.QRect(171, 56, 211, 24))
        self.usernameEntry.setObjectName("usernameEntry")
        self.passwordLabel = QtWidgets.QLabel(self.loginPage)
        self.passwordLabel.setGeometry(QtCore.QRect(100, 110, 61, 41))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordEntry = QtWidgets.QLineEdit(self.loginPage)
        self.passwordEntry.setGeometry(QtCore.QRect(171, 116, 211, 24))
        self.passwordEntry.setObjectName("passwordEntry")
        self.stackedWidget.addWidget(self.loginPage)
        self.AddUserPage = QtWidgets.QWidget()
        self.AddUserPage.setObjectName("AddUserPage")
        self.submitButton = QtWidgets.QPushButton(self.AddUserPage)
        self.submitButton.setGeometry(QtCore.QRect(240, 210, 101, 41))
        self.submitButton.setObjectName("submitButton")
        self.backButton = QtWidgets.QPushButton(self.AddUserPage)
        self.backButton.setGeometry(QtCore.QRect(120, 210, 101, 41))
        self.backButton.setObjectName("backButton")
        self.newUsernameLabel = QtWidgets.QLabel(self.AddUserPage)
        self.newUsernameLabel.setGeometry(QtCore.QRect(80, 50, 101, 51))
        self.newUsernameLabel.setObjectName("newUsernameLabel")
        self.newPasswordLabel = QtWidgets.QLabel(self.AddUserPage)
        self.newPasswordLabel.setGeometry(QtCore.QRect(80, 110, 101, 41))
        self.newPasswordLabel.setObjectName("newPasswordLabel")
        self.newUserNameEntry = QtWidgets.QLineEdit(self.AddUserPage)
        self.newUserNameEntry.setGeometry(QtCore.QRect(190, 70, 211, 24))
        self.newUserNameEntry.setObjectName("newUserNameEntry")
        self.newPasswordEntry = QtWidgets.QLineEdit(self.AddUserPage)
        self.newPasswordEntry.setGeometry(QtCore.QRect(190, 120, 211, 24))
        self.newPasswordEntry.setObjectName("newPasswordEntry")
        self.stackedWidget.addWidget(self.AddUserPage)

        self.retranslateUi(Widget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Elsa-Login Page"))
        self.addNewUserButton.setText(_translate("Widget", "Add New User"))
        self.verifyUserButton.setText(_translate("Widget", "Verify"))
        self.usernameLabel.setText(_translate("Widget", "Username:"))
        self.passwordLabel.setText(_translate("Widget", "Password:"))
        self.submitButton.setText(_translate("Widget", "Submit"))
        self.backButton.setText(_translate("Widget", "Back"))
        self.newUsernameLabel.setText(_translate("Widget", "New Username:"))
        self.newPasswordLabel.setText(_translate("Widget", "New Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
