# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 40, 761, 531))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.GRLabel = QtWidgets.QLabel(self.page)
        self.GRLabel.setGeometry(QtCore.QRect(-60, -80, 781, 461))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner Semibold")
        font.setPointSize(300)
        font.setBold(True)
        font.setWeight(75)
        self.GRLabel.setFont(font)
        self.GRLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GRLabel.setObjectName("GRLabel")
        self.GReatnessButton = QtWidgets.QPushButton(self.page)
        self.GReatnessButton.setGeometry(QtCore.QRect(550, 480, 191, 28))
        self.GReatnessButton.setObjectName("GReatnessButton")
        self.GReatnessButton.clicked.connect(self.topage2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.LicenseText = QtWidgets.QLabel(self.page_2)
        self.LicenseText.setGeometry(QtCore.QRect(-30, -90, 761, 551))
        self.LicenseText.setAlignment(QtCore.Qt.AlignCenter)
        self.LicenseText.setObjectName("LicenseText")
        self.AgreePushButton = QtWidgets.QRadioButton(self.page_2)
        self.AgreePushButton.setGeometry(QtCore.QRect(20, 430, 95, 20))
        self.AgreePushButton.setObjectName("AgreePushButton")
        self.AgreePushButton.clicked.connect(self.agreeradioevent)
        self.DisAgreeRadioButton = QtWidgets.QRadioButton(self.page_2)
        self.DisAgreeRadioButton.setGeometry(QtCore.QRect(20, 460, 95, 20))
        self.DisAgreeRadioButton.setObjectName("DisAgreeRadioButton")
        self.DisAgreeRadioButton.clicked.connect(self.disagreeradioevent)
        self.ExitButton = QtWidgets.QPushButton(self.page_2)
        self.ExitButton.setGeometry(QtCore.QRect(410, 470, 93, 28))
        self.ExitButton.setObjectName("ExitButton")
        self.ExitButton.clicked.connect(self.exitwin)
        self.ContinueButton = QtWidgets.QPushButton(self.page_2)
        self.ContinueButton.setGeometry(QtCore.QRect(530, 470, 93, 28))
        self.ContinueButton.setObjectName("ContinueButton")
        self.ContinueButton.clicked.connect(self.topage3)
        self.ContinueButton.setDisabled(True)

        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(-100, -50, 841, 571))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def agreeradioevent(self):
        self.ContinueButton.setDisabled(False)

    def disagreeradioevent(self):
        self.ContinueButton.setDisabled(True)

    def topage2(self):
        self.stackedWidget.setCurrentIndex(1)

    def topage3(self):
        self.stackedWidget.setCurrentIndex(2)

    def exitwin(self):
        sys.exit(app.exec_())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.LicenseText.setText(
            _translate(
                "MainWindow", "MIT License\n"
                "\n"
                "Copyright (c) 2021 George Rahul\n"
                "\n"
                "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
                "of this software and associated documentation files (the \"Software\"), to deal\n"
                "in the Software without restriction, including without limitation the rights\n"
                "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
                "copies of the Software, and to permit persons to whom the Software is\n"
                "furnished to do so, subject to the following conditions:\n"
                "\n"
                "The above copyright notice and this permission notice shall be included in all\n"
                "copies or substantial portions of the Software.\n"
                "\n"
                "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
                "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
                "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
                "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
                "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
                "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
                "SOFTWARE.\n"
                ""))
        self.AgreePushButton.setText(_translate("MainWindow", "I Agree"))
        self.DisAgreeRadioButton.setText(_translate("MainWindow",
                                                    "I Disagree"))

        self.ExitButton.setText(_translate("MainWindow", "Exit"))
        self.ContinueButton.setText(_translate("MainWindow", "Continue"))
        self.label.setText(
            _translate("MainWindow", "The GReatness\n"
                       "Unleashed"))
        self.GRLabel.setText(_translate("MainWindow", "GR"))
        self.GReatnessButton.setText(
            _translate("MainWindow", "Continue to the GReatnes>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
