# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsettingspage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Magic import usergui,export_import,history,indexer
from functools import partial
from talk1.talk1 import talk
from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter.filedialog import askdirectory
import os


class Ui_MainWindow(object):
    def __init__(self,username):
        self.username= username
    def setupUi(self, MainWindow):
        #MainWindow.setStyleSheet('background-color: red;')
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingsPage = QtWidgets.QTabWidget(self.centralwidget)
        self.SettingsPage.setGeometry(QtCore.QRect(0, 0, 751, 541))
        self.SettingsPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SettingsPage.setTabsClosable(False)
        self.SettingsPage.setMovable(True)
        self.SettingsPage.setTabBarAutoHide(False)
        self.SettingsPage.setObjectName("SettingsPage")
        self.GeneralTab = QtWidgets.QWidget()
        self.GeneralTab.setObjectName("GeneralTab")
        self.AddUserButton = QtWidgets.QPushButton(self.GeneralTab)
        self.AddUserButton.setGeometry(QtCore.QRect(120, 0, 121, 51))
        self.AddUserButton.setObjectName("AddUserButton")
        self.AddUserButton.clicked.connect(self.usr_page)
        self.DeleteUserButton = QtWidgets.QPushButton(self.GeneralTab)
        self.DeleteUserButton.setGeometry(QtCore.QRect(120, 60, 121, 51))
        self.DeleteUserButton.setObjectName("DeleteUserButton")
        self.DeleteUserButton.clicked.connect(usergui.deleteuser)
        self.ImportDataButton = QtWidgets.QPushButton(self.GeneralTab)
        self.ImportDataButton.setGeometry(QtCore.QRect(120, 120, 121, 51))
        self.ImportDataButton.setObjectName("ImportDataButton")
        self.ImportDataButton.clicked.connect(export_import.import_data)
        self.ExportDataButton = QtWidgets.QPushButton(self.GeneralTab)
        self.ExportDataButton.setGeometry(QtCore.QRect(120, 180, 121, 51))
        self.ExportDataButton.setObjectName("ExportDataButton")
        self.ExportDataButton.clicked.connect(export_import.export)
        self.SettingsPage.addTab(self.GeneralTab, "")
        self.AboutTab_2 = QtWidgets.QWidget()
        self.AboutTab_2.setObjectName("AboutTab_2")
        self.VersionLabel = QtWidgets.QLabel(self.AboutTab_2)
        self.VersionLabel.setGeometry(QtCore.QRect(110, 10, 161, 31))
        self.VersionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VersionLabel.setObjectName("VersionLabel")
        self.CreatedNamesLabel = QtWidgets.QLabel(self.AboutTab_2)
        self.CreatedNamesLabel.setGeometry(QtCore.QRect(70, 60, 251, 151))
        self.CreatedNamesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CreatedNamesLabel.setObjectName("CreatedNamesLabel")
        self.CreatedByLabel = QtWidgets.QLabel(self.AboutTab_2)
        self.CreatedByLabel.setGeometry(QtCore.QRect(150, 90, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CreatedByLabel.setFont(font)
        self.CreatedByLabel.setObjectName("CreatedByLabel")
        self.SettingsPage.addTab(self.AboutTab_2, "")
        self.HistoryTab = QtWidgets.QWidget()
        self.HistoryTab.setObjectName("HistoryTab")
        self.ShowHistoryButton = QtWidgets.QPushButton(self.HistoryTab)
        self.ShowHistoryButton.setGeometry(QtCore.QRect(130, 20, 101, 61))
        self.ShowHistoryButton.setObjectName("ShowHistoryButton")
        self.ShowHistoryButton.clicked.connect(partial(history.user_read, username=self.username))
        self.DeleteHistoryButton = QtWidgets.QPushButton(self.HistoryTab)
        self.DeleteHistoryButton.setGeometry(QtCore.QRect(130, 90, 101, 61))
        self.DeleteHistoryButton.setObjectName("DeleteHistoryButton")
        self.DeleteHistoryButton.clicked.connect(partial(history.clear_history,name=self.username))
        self.SettingsPage.addTab(self.HistoryTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.AddIndexerButton = QtWidgets.QPushButton(self.tab)
        self.AddIndexerButton.setGeometry(QtCore.QRect(130, 10, 131, 61))
        self.AddIndexerButton.setObjectName("AddIndexerButton")
        self.AddIndexerButton.clicked.connect(self.folderchoose)
        self.ResetIndexerButton = QtWidgets.QPushButton(self.tab)
        self.ResetIndexerButton.setGeometry(QtCore.QRect(130, 80, 131, 61))
        self.ResetIndexerButton.setObjectName("ResetIndexerButton")
        self.ResetIndexerButton.clicked.connect(self.resetindexercache)

        self.SettingsPage.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.SettingsPage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def folderchoose(self):
        folderpath = askdirectory()
        indexer.add_indexer_folders(path=folderpath)
        del folderpath

    def resetindexercache(self):
        try:
            talk("Reseted the cache")
            os.remove((os.getcwd() + "\\resources\\ indexer.elsa"))
            print("'indexer.elsa' is removed")
        except:pass    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Elsa Settings"))
        self.AddUserButton.setText(_translate("MainWindow", "Add User"))
        self.DeleteUserButton.setText(_translate("MainWindow", "Delete User"))
        self.ImportDataButton.setText(_translate("MainWindow", "Import Data"))
        self.ExportDataButton.setText(_translate("MainWindow", "Export Data"))
        self.SettingsPage.setTabText(self.SettingsPage.indexOf(self.GeneralTab), _translate("MainWindow", "General"))
        self.VersionLabel.setText(_translate("MainWindow", "Version:\n"
"Elsa 1.1"))
        self.CreatedNamesLabel.setText(_translate("MainWindow", "George Rahul\n"
"Elizabeth Jaison\n"
"Austin Bert Ambooken"))
        self.CreatedByLabel.setText(_translate("MainWindow", "Created By:"))
        self.SettingsPage.setTabText(self.SettingsPage.indexOf(self.AboutTab_2), _translate("MainWindow", "About"))
        self.ShowHistoryButton.setText(_translate("MainWindow", "Show History"))
        self.DeleteHistoryButton.setText(_translate("MainWindow", "Delete History"))
        self.SettingsPage.setTabText(self.SettingsPage.indexOf(self.HistoryTab), _translate("MainWindow", "History"))
        self.AddIndexerButton.setText(_translate("MainWindow", "Add Indexer Folder"))
        self.ResetIndexerButton.setText(_translate("MainWindow", "Reset Indexer Cache"))
        self.SettingsPage.setTabText(self.SettingsPage.indexOf(self.tab), _translate("MainWindow", "Indexer"))

    def usr_page(event=""):
        talk("Please add a new user")
        usergui.user_page()


def setting_page(event="", username="", state=True):
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('fusion')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(username)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
